include: package:very_good_analysis/analysis_options.6.0.0.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "build/**"
    - "lib/generated/**"
  
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    # Treat missing returns as errors
    missing_return: error
    # Treat missing required parameters as errors  
    missing_required_param: error
    # Treat invalid assignments as errors
    invalid_assignment: error
    # Allow TODO comments
    todo: ignore

linter:
  rules:
    # Additional rules for better code quality
    always_use_package_imports: true
    avoid_redundant_argument_values: true
    cascade_invocations: true
    conditional_uri_does_not_exist: true
    deprecated_consistency: true
    directives_ordering: true
    do_not_use_environment: true
    eol_at_end_of_file: true
    flutter_style_todos: true
    missing_whitespace_between_adjacent_strings: true
    no_default_cases: false
    package_api_docs: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_constructors_first: true
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true
    use_raw_strings: true
    use_string_buffers: true
    use_super_parameters: true
    use_to_and_as_if_applicable: true

    # Disable some rules that conflict with our standards
    public_member_api_docs: false
    lines_longer_than_80_chars: false
