name: adara_screen_digital_signage
description: "Professional Digital Signage Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  device_info_plus: ^10.1.0
  connectivity_plus: ^6.0.3
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  video_player: ^2.8.1
  webview_flutter: ^4.4.2
  cached_network_image: ^3.3.0
  flutter_animate: ^4.5.0
  mobile_scanner: ^3.5.6
  permission_handler: ^11.3.1
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/launch_video.mp4
    - assets/images/standby_screen.jpg